version: "3.7"
services: 
  php: 
    build: 
      args:
        user: ${OS_USER}
        uid: ${OS_UID}
      context: './config/php'
      dockerfile: Dockerfile
    volumes:
      - ./src:/var/www/html 
      - ./config/php/dev.ini:/usr/local/etc/php/conf.d/dev.ini

  mysql:
    image: mysql:5.7
    restart: always
    volumes:
      - ./database:/var/lib/mysql
    environment: 
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}

  phpmyadmin:
    depends_on: 
        - mysql
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
        - '${PHPMYADMIN_PORT}:80'
    environment: 
        PMA_HOST: mysql
        MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}

  nginx: 
    image: nginx:stable-alpine
    ports:
      - '${NGINX_PORT}:80'
    volumes:
      - ./src:/var/www/html
      - ./config/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - mysql