FROM php:7.4-fpm-alpine
# Arguments defined in docker-compose.yml
ARG user
ARG uid

# Install PHP extensions
RUN docker-php-ext-install pdo pdo_mysql

# Get latest Composer
COPY --from=composer:latest /usr/bin/composer /usr/bin/composer
# Get npm
# RUN apk add --update npm

USER root

RUN  adduser -G www-data -u $uid -h /home/$user -D $user && addgroup $user root && addgroup $user  && addgroup $user $user

RUN  chown -R $user:$user /var/www/html

RUN  chmod -R 755 /var/www/html

RUN mkdir -p /home/$user/.composer
RUN chown -R $user:$user /home/$user

USER $user